In [2]:
import numpy as np
from copy import deepcopy
V_table = np.array([[0, 0.2],
                    [0, 0  ],
                    [0, 0  ],
                    [0, 0  ],
                    [1, 0  ]])

transitions = {1: [1, 2], 
               2: [1, 3], 
               3: [1, 4], 
               4: [1, 5],
               5: [1, 5]}

r = [0.2, 0, 0, 0, 1]

gamma = 0.9

In [69]:
V_table = np.array([[0, 0.2],
                    [0, 0  ],
                    [0, 0  ],
                    [0, 0  ],
                    [1, 0  ]])

transitions = {1: [1, 2], 
               2: [1, 3], 
               3: [1, 4], 
               4: [1, 5],
               5: [1, 5]}

r = [0.2, 0, 0, 0, 1]

gamma = 0.9

old_V = deepcopy(V_table)
print(old_V)
print()



for state in range(len(V_table)):
    
    possible_trans = np.array(transitions[state+1]) - 1
    print(f'Transitions from state {state} : {possible_trans}')
    
    discounted_Vs = np.array([gamma * old_V[trans] for trans in possible_trans])
    print(f'Discounted_Vs:\n{discounted_Vs}')
    
    best_next_state = transitions[state+1][np.argmax([max(V) for V in discounted_Vs])]
    print(f'best_next_state: {best_next_state}')
    
    best_action = np.argmax([max(discounted_Vs[:,0]), max(discounted_Vs[:,1])])
    print(f'best_action: {best_action}')
    
    
#     discounted_V = discounted_Vs[best_next_state-1][best_action]
    discounted_V = old_V[best_next_state-1][best_action]
    
    V_table[state][best_a] = r[state] + gamma * discounted_V
    print(V_table)
    print()
    

# print(V_table)
    
    

[[0.  0.2]
 [0.  0. ]
 [0.  0. ]
 [0.  0. ]
 [1.  0. ]]

Transitions from state 0 : [0 1]
Discounted_Vs:
[[0.   0.18]
 [0.   0.  ]]
best_next_state: 1
best_action: 1
[[0.   0.38]
 [0.   0.  ]
 [0.   0.  ]
 [0.   0.  ]
 [1.   0.  ]]

Transitions from state 1 : [0 2]
Discounted_Vs:
[[0.   0.18]
 [0.   0.  ]]
best_next_state: 1
best_action: 1
[[0.   0.38]
 [0.   0.18]
 [0.   0.  ]
 [0.   0.  ]
 [1.   0.  ]]

Transitions from state 2 : [0 3]
Discounted_Vs:
[[0.   0.18]
 [0.   0.  ]]
best_next_state: 1
best_action: 1
[[0.   0.38]
 [0.   0.18]
 [0.   0.18]
 [0.   0.  ]
 [1.   0.  ]]

Transitions from state 3 : [0 4]
Discounted_Vs:
[[0.   0.18]
 [0.9  0.  ]]
best_next_state: 5
best_action: 0
[[0.   0.38]
 [0.   0.18]
 [0.   0.18]
 [0.   0.9 ]
 [1.   0.  ]]

Transitions from state 4 : [0 4]
Discounted_Vs:
[[0.   0.18]
 [0.9  0.  ]]
best_next_state: 5
best_action: 0
[[0.   0.38]
 [0.   0.18]
 [0.   0.18]
 [0.   0.9 ]
 [1.   1.9 ]]



In [57]:
test = np.array([[0.21, 0.22],
                [0.23,   0.23]])


np.argmax([max(test[:,0]), max(test[:,1])])
# print(best_action)

0